### ISSUE TITLE
Need help with building

### ISSUE THREAD

**Issue by BamaJoe411** [z3ntu/RazerGenie#98]
I just cloned the git to build RazerGenie and got these errors when building.

```
bamajoe411@jb-ubuntu-zbook:~/Documents/gits/RazerGenie$ ./builddir/src/razergenie 
Translation loaded: false
Invalid backend value. Using openrazer backend.
DeviceListWidget: Received errored signal!
DeviceListWidget: Reason: "Image download disabled"
DeviceListWidget: Long reason: "Image downloading is disabled. Visit the preferences to enable it."
DeviceListWidget: Received errored signal!
DeviceListWidget: Reason: "Image download disabled"
DeviceListWidget: Long reason: "Image downloading is disabled. Visit the preferences to enable it."
libopenrazer: There was an error in virtual uchar libopenrazer::openrazer::Led::getBrightness()
libopenrazer: org.freedesktop.DBus.Python.ValueError
libopenrazer: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py", line 21, in get_brightness
    brightness = round(float(driver_file.read()) * (100.0 / 255.0), 2)
ValueError: could not convert string to float: ''

terminate called after throwing an instance of 'libopenrazer::DBusException'
  what():  std::exception
Aborted (core dumped)

**Comment by z3ntu** [comment]
What device are you using? 

Can you also give the output of `tail /sys/bus/hid/drivers/razer*/0*/matrix_brightness` ?

**Comment by BamaJoe411** [comment]
there is no output when running that command
also this is my mouse
``` Bus 003 Device 008: ID 1532:0067 Razer USA, Ltd Razer Naga Trinity

**Comment by z3ntu** [comment]
Can you check if there are errors from the kernel modules (razer*) in dmesg? Also please run the `tail` command again but with `-v` additionally (`tail -v /sys/bus/hid/drivers/razer*/0*/matrix_brightness`)

**Comment by BamaJoe411** [comment]
```
bamajoe411@jb-ubuntu-zbook:~/Documents/gits/RazerGenie$ ./builddir/src/razergenie
Translation loaded: false
Invalid backend value. Using openrazer backend.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libopenrazer: There was an error in virtual uchar libopenrazer::openrazer::Led::getBrightness()
libopenrazer: org.freedesktop.DBus.Python.ValueError
libopenrazer: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py", line 21, in get_brightness
    brightness = round(float(driver_file.read()) * (100.0 / 255.0), 2)
ValueError: could not convert string to float: ''

terminate called after throwing an instance of 'libopenrazer::DBusException'
  what():  std::exception
Aborted (core dumped)


bamajoe411@jb-ubuntu-zbook:~/Documents/gits/RazerGenie$ dmesg | grep razer
[    8.682365] razerkraken: loading out-of-tree module taints kernel.
[    8.696131] razerkraken: module verification failed: signature and/or required key missing - tainting kernel
[    8.968437] razermouse 0003:1532:0067.0001: input,hidraw0: USB HID v1.11 Mouse [Razer Razer Naga Trinity] on usb-0000:00:14.0-2/input0
[    9.151669] razerkraken 0003:1532:0510.0004: input,hiddev0,hidraw3: USB HID v1.11 Device [Razer Razer Kraken 7.1 V2] on usb-0000:00:14.0-10/input3
[    9.359424] razermouse 0003:1532:0067.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Naga Trinity] on usb-0000:00:14.0-2/input1
[   10.015510] razermouse 0003:1532:0067.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Naga Trinity] on usb-0000:00:14.0-2/input2
[  222.632025] razermouse: Command failed. Start Marker: 03 id: 3f Num Params: 03 Reserved: 0f Command: 84 Params: 01000000000000000000000000000000 .
[  222.633744] razermouse: Command failed. Start Marker: 03 id: 3f Num Params: 03 Reserved: 0f Command: 84 Params: 01000000000000000000000000000000 .
[  247.999554] razermouse: Command failed. Start Marker: 03 id: 3f Num Params: 03 Reserved: 0f Command: 84 Params: 01000000000000000000000000000000 .


bamajoe411@jb-ubuntu-zbook:~/Documents/gits/RazerGenie$ tail -v /sys/bus/hid/drivers/razer*/0*/matrix_brightness
==> /sys/bus/hid/drivers/razermouse/0003:1532:0067.0001/matrix_brightness <==

**Comment by JohnOberhauser** [comment]
Getting the same thing with my naga trinity plugged in

**Comment by z3ntu** [comment]
Please test on latest master, this should be fixed now.
